//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public int iTemp { get; set; }
        public int idProduct { get; set; }
        public int id_order_temp { get; set; }
        public int count { get; set; }
    
        public virtual product product { get; set; }
    }
}
