USE [master]
GO

/****** Object:  Database [fahrutdinova]    Script Date: 24.11.2023 15:19:01 ******/
DROP DATABASE [fahrutdinova]
GO

/****** Object:  Database [fahrutdinova]    Script Date: 24.11.2023 15:19:01 ******/
CREATE DATABASE [fahrutdinova]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'fahrutdinova', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\fahrutdinova.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'fahrutdinova_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\fahrutdinova_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [fahrutdinova].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [fahrutdinova] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [fahrutdinova] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [fahrutdinova] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [fahrutdinova] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [fahrutdinova] SET ARITHABORT OFF 
GO

ALTER DATABASE [fahrutdinova] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [fahrutdinova] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [fahrutdinova] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [fahrutdinova] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [fahrutdinova] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [fahrutdinova] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [fahrutdinova] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [fahrutdinova] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [fahrutdinova] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [fahrutdinova] SET  DISABLE_BROKER 
GO

ALTER DATABASE [fahrutdinova] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [fahrutdinova] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [fahrutdinova] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [fahrutdinova] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [fahrutdinova] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [fahrutdinova] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [fahrutdinova] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [fahrutdinova] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [fahrutdinova] SET  MULTI_USER 
GO

ALTER DATABASE [fahrutdinova] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [fahrutdinova] SET DB_CHAINING OFF 
GO

ALTER DATABASE [fahrutdinova] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [fahrutdinova] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [fahrutdinova] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [fahrutdinova] SET QUERY_STORE = OFF
GO

ALTER DATABASE [fahrutdinova] SET  READ_WRITE 
GO

