//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emamBookClub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BoocClubEntities : DbContext
    {
        private static BoocClubEntities _context;
        public BoocClubEntities()
            : base("name=BoocClubEntities")
        {
        }
        public static BoocClubEntities GetContext()
        {
            if (_context == null)
                _context = new BoocClubEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<manufactirer> manufactirer { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderProduct> orderProduct { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<punkt> punkt { get; set; }
        public virtual DbSet<Rolee> Rolee { get; set; }
        public virtual DbSet<temp> temp { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
